import {useState} from 'react';
import {apiFetch} from './api/client';
async function call(path,method='GET',body){const r=await apiFetch(path,{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail));return d;}
export default function AccountControls({role}){
 const [data,setData]=useState(null),[integrity,setIntegrity]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[current,setCurrent]=useState(''),[password,setPassword]=useState(''),[target,setTarget]=useState(''),[reset,setReset]=useState('');
 const run=async fn=>{setBusy(true);setNotice('');try{await fn();}catch(e){setNotice(e.message);}finally{setBusy(false);}};
 const load=async()=>setData(await call('/api/admin/accounts'));
 const action=(username,action,password='')=>run(async()=>{if(!window.confirm(`${action.replaceAll('_',' ')} for ${username}?`))return;const r=await call('/api/admin/accounts/'+encodeURIComponent(username),'POST',{action,password});setNotice(r.message);setReset('');await load();});
 return <section className="panel registry-panel"><h2>Account and audit controls</h2><p>Sessions expire after 15 minutes without authenticated API requests, or after eight hours total. Background requests count as activity.</p>
 <form onSubmit={e=>{e.preventDefault();run(async()=>{const d=await call('/api/auth/password','POST',{current_password:current,new_password:password});setCurrent('');setPassword('');setNotice(d.message);window.location.reload();});}}>
 <label>Current password<input type="password" autoComplete="current-password" required value={current} onChange={e=>setCurrent(e.target.value)}/></label><label>New password<input type="password" autoComplete="new-password" minLength={12} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>Change password and sign out</button></form>
 {role==='supervisor'&&<><div className="registry-toolbar"><button disabled={busy} onClick={()=>run(load)}>Load accounts and sessions</button><button disabled={busy} onClick={()=>run(async()=>setIntegrity(await call('/api/admin/integrity')))}>Check audit integrity</button><a href="/api/admin/audit-checkpoint" download="audit-checkpoint.json">Download signed audit checkpoint</a></div>
 {data&&<><p>{data.session_policy}</p>{data.users.map(u=><div className="registry-toolbar" key={u.username}><span>{u.username} · {u.role} · {u.enabled?'Enabled':'Disabled'}</span><button disabled={busy} onClick={()=>action(u.username,u.enabled?'disable':'enable')}>{u.enabled?'Disable':'Enable'}</button><button disabled={busy} onClick={()=>action(u.username,'revoke_sessions')}>Revoke all sessions</button><button onClick={()=>setTarget(u.username)}>Reset password</button></div>)}
 {target&&<form onSubmit={e=>{e.preventDefault();action(target,'reset_password',reset);}}><label>New password for {target}<input type="password" autoComplete="new-password" required minLength={12} value={reset} onChange={e=>setReset(e.target.value)}/></label><button disabled={busy}>Confirm password reset</button></form>}
 <h3>Active sessions</h3>{data.sessions.map(s=><p key={s.id}>{s.username} · last API activity {new Date(s.last_seen*1000).toLocaleString()} <button disabled={busy} onClick={()=>run(async()=>{await call('/api/admin/sessions/'+s.id,'DELETE');await load();})}>Revoke session</button></p>)}
 <details><summary>Latest account/security events (up to 100)</summary>{(data.events||[]).map((e,i)=><p key={i}>{new Date(e.timestamp).toLocaleString()} · {e.actor} · {e.action} · {e.subject}</p>)}</details></>}
 {integrity&&<><p>{integrity.scope}</p>{['screening','registry','accounts'].map(k=><p key={k}>{k}: {integrity[k].status} · {integrity[k].count} events · {integrity[k].issues.join('; ')}<br/>{integrity[k].limitation}</p>)}</>}</>}
 {notice&&<p role="status">{notice}</p>}</section>;
}
