import {useEffect,useState} from 'react';
import DocumentInspector from './DocumentInspector';
import './workflow.css';
export const reviewFields=[['name','Name'],['dob','Date of birth'],['documentNumber','Document number'],['nationality','Nationality'],['issuerCountry','Issuing country'],['gender','Gender'],['issueDate','Issue date'],['expiry','Expiry'],['issuingAuthority','Issuing authority'],['passportReference','Passport reference'],['visaType','Visa type/class'],['numberOfEntries','Number of entries'],['validFrom','Valid from'],['durationOfStay','Duration of stay']];
export function requiredFields(type){return ['name','documentNumber','dob','nationality','issuerCountry',...(['Passport','Visa','Permit','Driving Licence','Travel Authorization'].includes(type)?['expiry']:[]),...(type==='Visa'?['passportReference','visaType','numberOfEntries','validFrom']:[])];}
export function DocumentReview({doc,index,updateDoc,disabled}){
 const [url,setUrl]=useState(''),[zoom,setZoom]=useState(1);
 useEffect(()=>{const value=URL.createObjectURL(doc.file);setUrl(value);return()=>URL.revokeObjectURL(value);},[doc.file]);
 const visaOnly=new Set(['passportReference','visaType','numberOfEntries','validFrom','durationOfStay']);
 const keys=reviewFields.filter(([k])=>!visaOnly.has(k)||doc.type==='Visa');
 const missing=requiredFields(doc.type).filter(k=>!doc.fields?.[k]?.trim());
 return <fieldset className="review-document" disabled={disabled}><legend>{doc.file.name} · OCR {Math.round(doc.ocrConfidence)}%</legend>
 {(doc.ocrNotes?.warnings||[]).map((v,i)=><p className="review-warning" key={'w'+i}>{v}</p>)}
 {!!doc.ocrNotes?.disagreements?.length&&<div className="registry-scroll"><table><thead><tr><th>Disagreeing field</th><th>Retained OCR read</th><th>Alternative OCR read</th></tr></thead><tbody>{doc.ocrNotes.disagreements.map(k=><tr key={k}><th>{k}</th><td>{doc.rawFields?.[k]||'Not extracted'}</td><td>{doc.ocrNotes.alternative?.fields?.[k]||'Not extracted'}</td></tr>)}</tbody></table><p>Choose only what you can read on the original; edit the field below to record an officer correction.</p></div>}
 {(doc.ocrNotes?.preparation?.guidance||[]).map((v,i)=><p key={'g'+i}>{v}</p>)}
 <DocumentInspector src={url} boxes={doc.ocrNotes?.field_boxes} fields={doc.fields} rawFields={doc.rawFields}/>
 {doc.alignmentPreview&&<details><summary>Perspective-corrected preview — inspection only</summary><p>This is a candidate crop, not the original. Check every edge. It is NOT used for OCR or QR verification in this release.</p><img className="alignment-preview" src={doc.alignmentPreview.image} alt="Candidate perspective-corrected document"/><p>{doc.alignmentPreview.status} · Original evidence retained.</p></details>}
 {doc.preparedPreview&&<details><summary>OCR working-copy preview (original retained)</summary><img className="evidence-image" src={doc.preparedPreview} alt="QR-excluded OCR working copy"/><p>If visible text was masked, untick preparation and extract again using the original image.</p></details>}
 <div className="review-split"><div><label>Image zoom<select value={zoom} onChange={e=>setZoom(Number(e.target.value))}>{[1,1.5,2,3].map(v=><option key={v} value={v}>{v}×</option>)}</select></label><div className="review-image-scroll"><img src={url} alt={'Original upload '+doc.file.name} style={{width:`${zoom*100}%`,maxWidth:'none'}}/></div><details><summary>Raw OCR text (unchanged engine output)</summary><pre>{doc.ocrText||'No text extracted'}</pre><p>OCR input: {doc.ocrNotes?.preparation?.method||'Not recorded'}. Original uploaded bytes remain separate.</p></details><details><summary>Extraction source values and warnings</summary><pre>{JSON.stringify(doc.ocrNotes,null,2)}</pre></details></div><div><p>Dates: DD/MM/YYYY or YYYY-MM-DD. Issuing country and nationality are separate fields. Correct only from the image.</p>{missing.length>0&&<p className="review-warning" role="status">Incomplete comparison fields: {missing.join(', ')}. You may submit for review; missing values cannot be treated as verified.</p>}{keys.map(([key,label])=>{const before=doc.rawFields?.[key]||'',value=doc.fields?.[key]||'',changed=value!==before;return <label className={'review-field '+(changed?'field-changed':'')} key={key}>{label}<small>Parsed OCR: {before||'Not extracted'}</small><input aria-label={label} maxLength={180} value={value} onChange={e=>updateDoc(index,{fields:{...doc.fields,[key]:e.target.value}})}/>{changed&&<small>Officer correction — retained in evidence</small>}{key==='name'&&/[0-9]/.test(value)&&<small className="review-warning">Digit in name: inspect the image. Do not silently replace it.</small>}</label>;})}</div></div></fieldset>;
}
export function ExtractionEvidence({extraction}){
 if(!extraction)return <section className="panel registry-panel"><h3>OCR review evidence</h3><p>No extraction snapshot available for this legacy record.</p></section>;
 const x=extraction;return <section className="panel registry-panel"><h3>OCR review evidence</h3><p>Submitted by {x.reviewed_by||'not recorded'} at {x.reviewed_at||'not recorded'}. Browser-supplied extraction; not independently attested.</p><details><summary>Raw OCR, parsed values and officer corrections</summary><pre className="raw-ocr">{x.raw_text}</pre><div className="registry-scroll"><table><thead><tr><th>Field</th><th>Parsed OCR</th><th>Reviewed value</th><th>Changed?</th></tr></thead><tbody>{Object.entries(x.reviewed_fields||{}).map(([k,v])=><tr key={k}><th>{k}</th><td>{x.parsed_fields?.[k]||'—'}</td><td>{v||'—'}</td><td>{!x.parsed_fields_supplied?'Not recorded':(x.corrections||[]).some(c=>c.field===k)?'Yes':'No'}</td></tr>)}</tbody></table></div></details></section>;
}
export function EvidenceSummary({analysis,face={},liveness={status:'NOT_RUN'}}){
 const hasPersonResult=!!face.status&&!['NOT_RUN','SKIPPED','OPTIONAL_NOT_RUN'].includes(face.status);
 const hasLivenessResult=!!liveness.status&&!['NOT_RUN','SKIPPED','OPTIONAL_NOT_RUN'].includes(liveness.status);
 return <section className="panel registry-panel"><h2>Screening summary</h2><div className="evidence-summary" style={{gridTemplateColumns:hasPersonResult||hasLivenessResult?undefined:"repeat(2, minmax(0, 1fr))"}}><div><h3>Document checks</h3><p>MRZ: {analysis.mrz_status||'Not run'}</p><p>Tamper anomaly: {analysis.forensic_assist?.tamper_ai?.status||'NOT RUN'}</p><p>Photo substitution: {analysis.forensic_assist?.photo_substitution?.status||'NOT RUN'}</p><p>Visa fields: {analysis.visa_intelligence?.status||'NOT APPLICABLE'} · Stamp/seal: {analysis.forensic_assist?.stamp_seal?.status||'NOT APPLICABLE'}</p></div><div><h3>Registry comparison</h3><p>{analysis.registry?.status||'NOT RUN'}</p><p>Synthetic reference only—not authenticity proof.</p></div>{(hasPersonResult||hasLivenessResult)&&<div><h3>Person comparison</h3><p>Face: {face.status||'NOT_RUN'}</p>{hasLivenessResult&&<p>Active liveness: {liveness.status}</p>}<p>Face similarity is not an identity probability; active liveness is prototype replay resistance, not certified PAD.</p></div>}</div></section>;
}
