import {useEffect,useState} from 'react';
import {apiFetch} from './api/client';
import './registry.css';
import RegistryGraph from './console/RegistryGraph';

const types=['Passport','Visa','Aadhaar Card','Voter ID (EPIC)','Driving Licence','PAN Card','National ID','Permit','Travel Authorization'];
const fields=['document_number','name','dob','nationality','issuer_country','gender','issue_date','expiry','issuing_authority','passport_reference','visa_type','number_of_entries','valid_from','duration_of_stay'];
const empty={document_type:'Permit',document_number:'',name:'',dob:'',nationality:'IND',issuer_country:'IND',gender:'',issue_date:'',expiry:'',issuing_authority:'',passport_reference:'',visa_type:'',number_of_entries:'',valid_from:'',duration_of_stay:'',status:'ACTIVE',requires_signed_qr:false};
const label=k=>k.replaceAll('_',' ');
async function request(path,method='GET',body){const r=await apiFetch('/api/registry'+path,{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail||'Request failed'));return d;}

export function RegistryComparison({value}){
 return <section className="panel registry-panel"><h2>Synthetic registry comparison</h2><p>Demonstration data only. No government connection. Matching data does not establish document authenticity.</p>
 {!value?<p>Not run for this legacy screening. Start a new screening to compare it.</p>:<><h3>{value.status.replaceAll('_',' ')}</h3><p>{value.message}</p><small>Checked {value.checked_at} · {value.record?`${value.record.id} · version ${value.record.version}`:'No record selected'}</small>
 <div className="registry-scroll"><table><thead><tr><th>Field</th><th>Reviewed upload value</th><th>Registry value</th><th>Result</th></tr></thead><tbody>{value.fields.map(f=><tr key={f.field}><th>{f.label}</th><td>{f.uploaded||'—'}</td><td>{f.registry||'—'}</td><td className={f.status==='CONFLICT'?'registry-error':''}>{label(f.status)}</td></tr>)}</tbody></table></div><p>This saved comparison retains the registry version used at screening time.</p></>}
 </section>;
}

export default function RegistryPage({role}){
 const supervisor=role==='supervisor';
 const [q,setQ]=useState(''),[archived,setArchived]=useState(false),[offset,setOffset]=useState(0),[data,setData]=useState({records:[],total:0}),[selected,setSelected]=useState(null),[form,setForm]=useState(null),[reason,setReason]=useState(''),[history,setHistory]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;request(`?q=${encodeURIComponent(q)}&include_archived=${archived}&offset=${offset}`).then(d=>{if(active){setData(d);setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[q,archived,offset,revision]);
 const choose=r=>{setSelected(r);setForm(Object.fromEntries(Object.keys(empty).map(k=>[k,r[k]??empty[k]])));setReason('');setHistory(null);setError('');};
 const perform=async fn=>{setBusy(true);setError('');setNotice('');try{await fn();setRevision(v=>v+1);}catch(e){setError(e.message);}finally{setBusy(false);}};
 const save=e=>{e.preventDefault();perform(async()=>{const saved=await request(selected?'/'+selected.id:'',selected?'PUT':'POST',{record:form,reason,...(selected?{expected_version:selected.version}:{})});choose(saved);setNotice('Record saved with audit history.');});};
 return <div className="content registry-page"><div className="eyebrow">LOCAL / DEMONSTRATION</div><h1>Synthetic demo registry</h1><p>Fictional reference records for presentations—not a government database. Officers can search and verify; supervisors can manage records.</p><RegistryGraph role={role}/>
 <div className="registry-toolbar"><label>Search name or number<input value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/></label><label><input type="checkbox" checked={archived} onChange={e=>{setArchived(e.target.checked);setOffset(0);}}/> Include archived</label>
 {supervisor&&<><button className="secondary-btn" disabled={busy} onClick={()=>{setSelected(null);setForm({...empty});setHistory(null);setReason('');}}>Add record</button><button className="secondary-btn" disabled={busy} onClick={()=>perform(async()=>{const d=await request('/demo-seed','POST');setNotice(`Loaded ${d.created.length} fictional records. ${d.skipped.length} existing records unchanged.`);})}>Load demo records</button></>}</div>
 {supervisor&&<button className="secondary-btn" disabled={busy} onClick={()=>perform(async()=>{const r=await apiFetch('/api/registry/visa-demo-seed',{method:'POST'});const d=await r.json();if(!r.ok)throw Error(d.detail);setNotice(`Visa demo: ${d.created.length} created; ${d.skipped.length} preserved. Use demo_samples/visa_intelligence.`);})}>Load v6.0 visa demo record</button>}
 {supervisor&&<button disabled={busy} onClick={()=>perform(async()=>{const r=await apiFetch('/api/signed-demo/seed',{method:'POST'});const d=await r.json();if(!r.ok)throw Error(d.detail);setNotice(`Signed QR demo: ${d.created.length} created; ${d.skipped.length} preserved.`);})}>Load signed QR demo records</button>}
 {error&&<p role="alert" className="registry-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {supervisor&&<button className="secondary-btn" disabled={busy} onClick={()=>perform(async()=>{const r=await apiFetch('/api/video-demo/seed',{method:'POST'});const d=await r.json();if(!r.ok)throw Error(d.detail);setNotice(`Video demo: ${d.created.length} created; ${d.skipped.length} existing records preserved. Use demo_samples/video_demo and its guide.`);})}>Load v5.6 video demo records</button>}
 <section className="panel registry-panel"><div className="registry-scroll"><table><thead><tr><th>Name</th><th>Document</th><th>Number</th><th>Status</th><th>Version</th><th>Open</th></tr></thead><tbody>{data.records.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.document_type} / {r.issuer_country}</td><td>{r.document_number}</td><td>{r.archived?'ARCHIVED':r.status}</td><td>{r.version}</td><td><button className="secondary-btn" onClick={()=>choose(r)}>View record</button></td></tr>)}</tbody></table></div>{!data.records.length&&<p>No records found. A supervisor can add fictional records or load the demo set.</p>}
 <div className="registry-toolbar"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous</button><span>{data.total} records</span><button disabled={offset+25>=data.total} onClick={()=>setOffset(offset+25)}>Next</button></div></section>
 {form&&<section className="panel registry-panel"><h2>{selected?'Record details':'New fictional record'}</h2>{selected&&<><p>{selected.id} · version {selected.version} · last changed by {selected.updated_by} {selected.archived?'· ARCHIVED':''}</p><a href={'/api/registry/'+selected.id} download={selected.id+'.json'}>Download reference JSON for separate demo issuer</a></>}
 <form onSubmit={save}><fieldset disabled={!supervisor||busy||selected?.archived} className="registry-form"><label>Document type<select value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value})}>{types.map(t=><option key={t}>{t}</option>)}</select></label>{fields.filter(k=>!['visa_type','number_of_entries','valid_from','duration_of_stay'].includes(k)||form.document_type==='Visa').map(k=><label key={k}>{label(k)}{k==='gender'?<select value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}>{['','M','F','X'].map(v=><option key={v}>{v}</option>)}</select>:<input required={['name','document_number','dob','nationality','issuer_country'].includes(k)} type={['dob','issue_date','expiry','valid_from'].includes(k)?'date':'text'} value={form[k]} maxLength={k.includes('country')||k==='nationality'?3:180} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</label>)}<label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['ACTIVE','EXPIRED','REVOKED','BLOCKED'].map(s=><option key={s}>{s}</option>)}</select></label></fieldset>
 <label><input type="checkbox" disabled={!supervisor||busy||selected?.archived} checked={!!form.requires_signed_qr} onChange={e=>setForm({...form,requires_signed_qr:e.target.checked})}/> Require signed demo QR for this reference</label>
 {supervisor&&<><label className="registry-reason">Reason for change (at least 10 characters)<textarea required minLength={10} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="primary-btn" disabled={busy||selected?.archived}>Save record</button></>}</form>
 {selected&&<div className="registry-toolbar"><button className="secondary-btn" disabled={busy} onClick={()=>perform(async()=>choose(await request('/'+selected.id)))}>Reload latest version</button>{supervisor&&<><button className="secondary-btn" disabled={busy||reason.trim().length<10} onClick={()=>perform(async()=>{choose(await request(`/${selected.id}/archive?restore=${!!selected.archived}`,'POST',{expected_version:selected.version,reason}));setNotice('Archive state updated; original history retained.');})}>{selected.archived?'Restore record':'Archive record'}</button><button className="secondary-btn" disabled={busy} onClick={()=>perform(async()=>setHistory(await request('/'+selected.id+'/history')))}>View change history</button></>}</div>}
 {history&&<div><h3>Change history ({history.total})</h3><p>Latest 50 changes. Records are versioned; archiving does not delete evidence.</p>{history.items.map(h=><details key={h.version}><summary>Version {h.version} · {h.action} · {h.actor} · {h.timestamp}</summary><p>{h.reason}</p><div className="registry-scroll"><table><thead><tr><th>Field</th><th>Before</th><th>After</th></tr></thead><tbody>{[...Object.keys(empty),'archived'].filter(k=>h.before?.[k]!==h.after[k]).map(k=><tr key={k}><th>{label(k)}</th><td>{String(h.before?.[k]??'—')}</td><td>{String(h.after[k]??'—')}</td></tr>)}</tbody></table></div></details>)}</div>}
 </section>}</div>;
}
