import {useRef,useState} from 'react';
import {EvidenceSection,Metrics,label} from './EvidencePanels';
import {requestJSON,useLocalResource} from './LocalResource';

function Table({rows=[],columns}){return <div className="registry-scroll"><table><thead><tr>{columns.map(([key,title])=><th key={key}>{title}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map(([key])=><td key={key}>{String(r[key]??'—')}</td>)}</tr>)}</tbody></table>{!rows.length&&<p>No records.</p>}</div>;}
const fields={
 link:[['record_id','Existing document record ID'],['relationship','Relationship',['LINKED','PRIMARY','PREVIOUS','REPLACEMENT']]],
 travel:[['event_type','Event',['ENTRY','EXIT','VISA_ISSUED','STAMP_OBSERVED']],['event_date','Event date','date'],['country_code','Country code'],['port','Port'],['document_record_id','Linked document record ID (optional)'],['authority','Authority'],['stamp_reference','Stamp reference']],
 alert:[['alert_type','Alert type',['IDENTITY_REVIEW','WATCHLIST_REVIEW','LOST_STOLEN_DOCUMENT','DUPLICATE_IDENTITY','DOCUMENT_REVOKED','DOCUMENT_BLOCKED','INFORMATION']],['severity','Severity',['REVIEW','HIGH','CRITICAL','INFO']],['document_record_id','Linked document record ID (optional)']]
};
function ActionForm({kind,onSubmit,busy}){
 const title={link:'Link document',travel:'Add travel / stamp event',alert:'Add synthetic alert'}[kind];
 return <form className="console-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));onSubmit(kind,values).then(ok=>{if(ok)form.reset();});}}><fieldset disabled={busy}><legend>{title}</legend>{fields[kind].map(([key,title,type])=><label key={key}>{title}{Array.isArray(type)?<select name={key}>{type.map(v=><option key={v}>{v}</option>)}</select>:<input name={key} type={type||'text'} required={['record_id','event_date'].includes(key)} maxLength={key==='country_code'?3:180}/>}</label>)}<label className="wide">Reason (at least 10 characters)<input name="reason" minLength={10} maxLength={500} required/></label><button className="secondary-btn" type="submit" disabled={busy}>{title}</button></fieldset></form>;
}
export function IdentityDetails({id,supervisor,onBack}){
 const [revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[resolving,setResolving]=useState(null);const working=useRef(false);
 const resource=useLocalResource('/api/registry2/identities/'+encodeURIComponent(id),revision);
 async function mutate(path,body){if(working.current)return false;working.current=true;setBusy(true);setError('');setNotice('');try{await requestJSON(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setNotice('Change saved with audit history.');setResolving(null);setRevision(x=>x+1);return true;}catch(e){setError(e.message);return false;}finally{working.current=false;setBusy(false);}}
 const submit=(kind,body)=>mutate('/api/registry2/identities/'+encodeURIComponent(id)+{link:'/link-document',travel:'/travel-events',alert:'/alerts'}[kind],{...body,...(kind!=='link'?{source:'SYNTHETIC_DEMO'}:{})});
 const d=resource.data;
 return <><button className="secondary-btn" onClick={onBack}>Back to identities</button>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{resource.loading?<p role="status">Loading identity…</p>:resource.error?<><p role="alert">{resource.error}</p><button onClick={()=>setRevision(x=>x+1)}>Retry</button></>:d&&<><h3>{d.identity.canonical_name} · {d.identity.id}</h3><p>DOB {d.identity.dob} · {d.identity.nationality} · {d.identity.identity_status}</p>
 <h3>Linked documents</h3><Table rows={d.documents} columns={[["document_type","Type"],["document_number","Number"],["issuer_country","Issuer"],["status","Status"],["id","Record"]]}/>
 <h3>Alerts</h3>{!(d.alerts||[]).length&&<p>No alerts recorded.</p>}{(d.alerts||[]).map(a=><article className="console-notice" key={a.id}><strong>{label(a.alert_type)} · {a.severity} · {a.status}</strong><p>{a.reason}</p><small>{a.source} · {a.document_record_id||'Identity-level'}</small>{supervisor&&a.status==='OPEN'&&<button className="secondary-btn" disabled={busy} onClick={()=>setResolving(a.id)}>Resolve alert</button>}{resolving===a.id&&<form onSubmit={e=>{e.preventDefault();mutate('/api/registry2/alerts/'+encodeURIComponent(a.id)+'/resolve',{reason:new FormData(e.currentTarget).get('reason')});}}><label>Resolution reason<input name="reason" required minLength={10} maxLength={500}/></label><button disabled={busy}>Save resolution</button><button type="button" onClick={()=>setResolving(null)}>Cancel</button></form>}</article>)}
 <h3>Travel / stamp history</h3><Table rows={d.travel_events} columns={[["event_date","Date"],["event_type","Event"],["country_code","Country"],["port","Port"],["authority","Authority"],["stamp_reference","Stamp reference"]]}/>
 <h3>Document relationships</h3><Table rows={d.document_relations} columns={[["relation_type","Relationship"],["from_record_id","From"],["to_record_id","To"]]}/>
 <p>Biometric reference metadata records: {d.biometric_references?.length??0}. Raw camera images are not stored here.</p>
 {supervisor&&<EvidenceSection title="Supervisor registry actions">{['link','travel','alert'].map(kind=><EvidenceSection key={kind} title={{link:'Link a document',travel:'Add travel evidence',alert:'Add an alert'}[kind]}><ActionForm kind={kind} onSubmit={submit} busy={busy}/></EvidenceSection>)}</EvidenceSection>}</>}
 </>;
}
export default function RegistryGraph({role}){
 const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const working=useRef(false);
 const summary=useLocalResource('/api/registry2/summary',revision),list=useLocalResource(selected?null:'/api/registry2/identities?q='+encodeURIComponent(search)+'&limit=25',revision);
 async function seed(path){if(working.current)return;working.current=true;setBusy(true);setError('');setNotice('');try{await requestJSON(path,{method:'POST'});setNotice('Fictional reference set prepared. Existing records preserved.');setRevision(x=>x+1);}catch(e){setError(e.message);}finally{working.current=false;setBusy(false);}}
 return <section className="panel registry-panel"><h2>Synthetic Registry 2.2: linked identities</h2><p>Local fictional identities link documents, travel records, alerts and issuer references. No government connection.</p>{summary.data&&<Metrics items={Object.entries(summary.data.counts||{}).map(([k,v])=>[label(k),v])}/>} {summary.error&&<p role="alert">{summary.error}</p>}
 {role==='supervisor'&&<EvidenceSection title="Prepare individual reference sets"><div className="console-tools">{[['Identity graph','/api/registry2/demo-seed'],['Visual issuer references','/api/registry2/demo-seed-visual-v66'],['Travel histories','/api/registry2/demo-seed-travel-v67']].map(([name,path])=><button key={path} className="secondary-btn" disabled={busy} onClick={()=>seed(path)}>{name}</button>)}</div></EvidenceSection>}
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {selected?<IdentityDetails key={selected} id={selected} supervisor={role==='supervisor'} onBack={()=>{setSelected(null);setRevision(x=>x+1);}}/>:<><form className="console-tools" onSubmit={e=>{e.preventDefault();setSearch(query);setRevision(x=>x+1);}}><label>Search linked identities <input value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="secondary-btn">Search identities</button></form>{list.loading?<p role="status">Loading identities…</p>:list.error?<p role="alert">{list.error}</p>:<div className="registry-scroll"><table><thead><tr><th>Identity</th><th>DOB</th><th>Nationality</th><th>Status</th><th>Details</th></tr></thead><tbody>{(list.data?.identities||[]).map(i=><tr key={i.id}><td>{i.canonical_name}<br/><small>{i.id}</small></td><td>{i.dob}</td><td>{i.nationality}</td><td>{i.identity_status}</td><td><button className="secondary-btn" onClick={()=>setSelected(i.id)}>Open identity graph</button></td></tr>)}</tbody></table>{!list.data?.identities?.length&&<p>No matching identities. Try another search or load fictional references.</p>}<p>Up to 25 matches. Refine your search for more specific results.</p></div>}</>}
 </section>;
}
